name: Create issue on commit

on: [ push ]

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@latest
      with:
        persist-credentials: false
                  
    - name: Go setup
      uses: actions/setup-go@latest
             
    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@latest
      with: 
        token: ${{ secrets.TOKEN }}
        update-command: "'go get -u && go mod tidy && go build'"
        update-path: "'./test/go'" #optional
